// ShipmentDetailModal.tsx
// Auto-generated component — displays full shipment details in a modal dialog
// Generated by AI assistant — reviewed and fixed before integrating into production

import React, { useEffect, useState, useMemo } from 'react';
import {
  Modal,
  Box,
  Typography,
  Chip,
  Divider,
  Button,
  Stack,
  IconButton,
} from '@mui/material';
import { Close as CloseIcon } from '@mui/icons-material';
import type { Shipment } from '@/api/types';

// Fix #1: Replace `any` with proper Shipment type
interface ShipmentDetailModalProps {
  shipment: Shipment;
  open: boolean;
  onClose: () => void;
}

// Status badge colors — used for the status chip
const STATUS_BADGE_COLORS: Record<string, string> = {
  received: '#2196F3',
  sorting: '#FF9800',
  ready_to_dispatch: '#9C27B0',
  dispatched: '#00BCD4',
  delivered: '#4CAF50',
  on_hold: '#F44336',
  cancelled: '#9E9E9E',
};

// Formats an ISO 8601 timestamp to a human-readable local string
function formatTimestamp(iso: string): string {
  return new Date(iso).toLocaleString('id-ID', {
    dateStyle: 'medium',
    timeStyle: 'short',
  });
}

const ShipmentDetailModal: React.FC<ShipmentDetailModalProps> = ({
  shipment,
  open,
  onClose,
}) => {
  const [aiSuggestion, setAiSuggestion] = useState<string>('');
  const [isLoadingSuggestion, setIsLoadingSuggestion] = useState(false);
  // Fix #9: Add error state for fetch error handling
  const [suggestionError, setSuggestionError] = useState<string | null>(null);

  // Fix #3: Add dependency array [shipment.id, open]; only fetch when modal is open
  // Fix #4: Use response.body.getReader() for proper streaming instead of response.text()
  // Fix #9: Wrap in try/catch for error handling
  useEffect(() => {
    if (!open) return;

    let cancelled = false;
    setAiSuggestion('');
    setSuggestionError(null);
    setIsLoadingSuggestion(true);

    (async () => {
      try {
        const response = await fetch('/api/ai/route-suggestion', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            shipment_id: shipment.id,
            shipment_data: shipment,
          }),
        });

        if (!response.ok) throw new Error('Failed to fetch suggestion');
        if (!response.body) throw new Error('No response body');

        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let accumulated = '';

        while (true) {
          const { done, value } = await reader.read();
          if (done || cancelled) break;
          accumulated += decoder.decode(value, { stream: true });
          setAiSuggestion(accumulated);
        }
      } catch (err) {
        if (!cancelled) {
          setSuggestionError(err instanceof Error ? err.message : 'Unknown error');
        }
      } finally {
        if (!cancelled) {
          setIsLoadingSuggestion(false);
        }
      }
    })();

    return () => { cancelled = true; };
  }, [shipment.id, open]);

  // Fix #2: Guard against undefined carrier.phone (e.g., AnterAja)
  const carrierPhoneFormatted = useMemo(() => {
    if (!shipment.carrier.phone) return 'N/A';
    const parts = shipment.carrier.phone.split('-');
    if (parts.length >= 3) {
      return `(${parts[0]}) ${parts[1]}-${parts[2]}`;
    }
    return shipment.carrier.phone;
  }, [shipment.carrier.phone]);

  // Fix #5: Add shipment.status to dependency array (was empty [])
  const statusDisplay = useMemo(
    () => shipment.status.replace(/_/g, ' ').toUpperCase(),
    [shipment.status],
  );

  // Fix #6: Remove handleResetStatus — it mutated the prop directly which doesn't persist
  // and bypasses the status machine. Proper status transitions should go through
  // PATCH /api/shipments/:id/status. Removed the button entirely.

  return (
    <Modal open={open} onClose={onClose}>
      <Box
        sx={{
          position: 'absolute',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
          width: 540,
          bgcolor: 'background.paper',
          borderRadius: 1,
          p: 4,
          outline: 'none',
        }}
      >
        {/* Fix #8: Replace <div> close button with accessible IconButton */}
        <IconButton
          onClick={onClose}
          aria-label="Close"
          sx={{ position: 'absolute', top: 8, right: 8 }}
        >
          <CloseIcon />
        </IconButton>

        <Typography variant="h5" gutterBottom>
          Shipment Details
        </Typography>

        <Chip
          label={statusDisplay}
          sx={{
            backgroundColor: STATUS_BADGE_COLORS[shipment.status] ?? '#9E9E9E',
            color: '#ffffff',
            fontWeight: 'bold',
            mb: 2,
          }}
        />

        <Divider sx={{ mb: 2 }} />

        <Stack spacing={1.5}>
          <div>
            <Typography variant="caption" color="text.secondary">
              Shipment ID
            </Typography>
            <Typography variant="body1">{shipment.id}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Tracking ID
            </Typography>
            <Typography variant="body1" sx={{ wordBreak: 'break-all' }}>
              {shipment.tracking_id}
            </Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Carrier
            </Typography>
            <Typography variant="body1">{shipment.carrier.name}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Carrier Phone
            </Typography>
            <Typography variant="body1">{carrierPhoneFormatted}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Sender → Recipient
            </Typography>
            <Typography variant="body1">
              {shipment.sender} → {shipment.recipient}
            </Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Destination
            </Typography>
            <Typography variant="body1">{shipment.destination}</Typography>
          </div>

          <div>
            <Typography variant="caption" color="text.secondary">
              Created At
            </Typography>
            <Typography variant="body1">{formatTimestamp(shipment.created_at)}</Typography>
          </div>
        </Stack>

        <Divider sx={{ my: 2 }} />

        <Typography variant="subtitle2" gutterBottom>
          Notes
        </Typography>
        {/* Fix #7: Replace dangerouslySetInnerHTML with safe text rendering to prevent XSS */}
        <Typography variant="body2" color="text.secondary" sx={{ whiteSpace: 'pre-wrap' }}>
          {shipment.notes ?? 'No notes'}
        </Typography>

        <Divider sx={{ my: 2 }} />

        <Typography variant="subtitle2" gutterBottom>
          AI Routing Suggestion
        </Typography>
        <Typography variant="body2" color="text.secondary">
          {suggestionError
            ? `Error: ${suggestionError}`
            : isLoadingSuggestion
              ? 'Fetching suggestion...'
              : aiSuggestion || 'No suggestion available'}
        </Typography>

        <Stack direction="row" spacing={2} sx={{ mt: 3 }}>
          <Button variant="outlined" onClick={onClose}>
            Close
          </Button>
        </Stack>
      </Box>
    </Modal>
  );
};

export default ShipmentDetailModal;
